# Generated by Django 5.2.8 on 2025-11-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatalert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='threat_alerts/'),
        ),
    ]
