# Generated by Django 5.2.8 on 2025-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_threatalert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatalert',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
