# Generated by Django 5.2.8 on 2025-11-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_threatalert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatalert',
            name='category',
            field=models.CharField(choices=[('Disinformation', 'Disinformation / Fake News'), ('Military', 'Military'), ('Police', 'Police'), ('APF', 'APF'), ('NationalCyberCrime', 'National CyberCrime'), ('InternationalCyberCrime', 'International CyberCrime'), ('ElectionManipulation', 'Election Manipulation'), ('SocialEngineering', 'Social Engineering'), ('DataLeak', 'Data Leak'), ('Scam', 'Financial Scam'), ('Impersonation', 'Impersonation'), ('Malware', 'Malware / Infected Links'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
