# Generated by Django 5.2.8 on 2025-11-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_threatalert_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatalert',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video files', null=True, upload_to='threat_alerts/videos/'),
        ),
        migrations.AlterField(
            model_name='threatalert',
            name='category',
            field=models.CharField(choices=[('Genz', 'Genz'), ('People', 'People'), ('Protest', 'Protest'), ('Disinformation', 'Disinformation / Fake News'), ('Military', 'Military'), ('Police', 'Police'), ('APF', 'APF'), ('NationalCyberCrime', 'National CyberCrime'), ('InternationalCyberCrime', 'International CyberCrime'), ('ElectionManipulation', 'Election Manipulation'), ('SocialEngineering', 'Social Engineering'), ('DataLeak', 'Data Leak'), ('Scam', 'Financial Scam'), ('Impersonation', 'Impersonation'), ('Malware', 'Malware / Infected Links'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='threatalert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
    ]
