# Generated by Django 5.2.8 on 2025-11-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_threatalert_video_alter_threatalert_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(help_text='When the activity took place', max_length=255)),
                ('location', models.CharField(help_text='Where the activity took place', max_length=255)),
                ('leader', models.CharField(help_text='Name of the person in charge', max_length=255)),
                ('number', models.CharField(blank=True, help_text='Contact number, ID, or team number', max_length=50, null=True)),
                ('vehicle', models.CharField(blank=True, help_text='Type of vehicle used (e.g., Toyota Hilux, Motorcycle)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Details of the activity or event', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='threatalert',
            name='category',
            field=models.CharField(choices=[('Genz', 'Genz'), ('Chapagau', 'Chapagau'), ('UML', 'UML'), ('Bhrikuti Mandav', 'Bhrikuti Mandav'), ('Samakoshi', 'Samakoshi'), ('PM', 'PM'), ('People', 'People'), ('Protest', 'Protest'), ('Disinformation', 'Disinformation / Fake News'), ('Army', 'Army'), ('Police', 'Police'), ('APF', 'APF'), ('NationalCyberCrime', 'National CyberCrime'), ('InternationalCyberCrime', 'International CyberCrime'), ('ElectionManipulation', 'Election Manipulation'), ('SocialEngineering', 'Social Engineering'), ('DataLeak', 'Data Leak'), ('Scam', 'Financial Scam'), ('Impersonation', 'Impersonation'), ('Malware', 'Malware / Infected Links'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
