# Generated by Django 5.2.8 on 2025-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_currentinformation_alter_threatalert_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the news source', max_length=200)),
                ('url', models.URLField(help_text='Full TikTok or official URL', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Logo or favicon (optional)', null=True, upload_to='threat_alerts/source')),
            ],
            options={
                'verbose_name': 'News Source',
                'verbose_name_plural': 'News Sources',
                'ordering': ['name'],
            },
        ),
    ]
